data:
  image_dir: /mnt/disk3/anhnd2468/MagicBathyNet/puck_lagoon/img/test_depth
  depth_dir: /mnt/disk3/anhnd2468/MagicBathyNet/puck_lagoon/depth/aerial
  pairing: magic
  image_suffix: "*.tif"
  depth_suffixes_to_try: ["_depth", "_bathy", "_gt", "_label"]
  image_mode: rgb
  reflectance_scale: 255.0
  magic_negative_depth_valid: true

train:
  device: cuda
  gpu_id: 0

infer:
  rgb_only: false
  checkpoint: depth_anything_v2_vitl.pth
  encoder: vitl
  device: cuda
  gpu_id: 0
  input_size: 518
  output_dir: depth_anythingv2_infer_outputs_puck_test_depth
